[package]
name = "demo"
version = "0.1.0"
authors = ["Bruno Ricci <brricci@orange.fr"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "demo"
path = "src/bin/demo.rs"

[dependencies]
postgres = "0.19.2"
